### ISSUE TITLE
Aggregation Hit source type is wrapped with JsonData instead of an object of the parameterized type

### ISSUE THREAD

**Issue by tony-hizzle** [elastic/elasticsearch-java#111]
SearchResponse.hits().hits() returns a List of Hit objects parameterized with the Class type specified in the request.

TopHitsAggregate.hits().hits() returns a List of Hit objects parameterized as JsonData, which must be cast to the desired type using JsonData.to(). What is the reason for this?

https://github.com/elastic/elasticsearch-java/blob/a40523751d/java-client/src/main/java/co/elastic/clients/elasticsearch/_types/aggregations/TopHitsAggregate.java#L110

**Comment by swallez** [comment]
Aggregations form complex hierarchical structures and the vast majority of them do not return documents. Adding a generic parameter on nestabe aggregations because we _may_ use the top hits aggregation somewhere in the aggregation tree seemed unnecessarily complex.

This is why top hit results are returned wrapped in a `JsonData`, which can easily be converted into an application class with the `to(Class<T> clazz)` method.

**Comment by tony-hizzle** [comment]
Understood. Thanks.
