### ISSUE TITLE
`NodeInfoPath.repo` should be optional

### ISSUE THREAD

**Issue by swallez** [elastic/elasticsearch-java#305]
Reported in https://discuss.elastic.co/t/how-to-get-details-from-nodes-api-with-java-client/305732

**Comment by MrUmnyj** [comment]
I found this bug in 7.17.9 version too.
The method given by the link https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/missing-required-property.html is not working because on the co.elastic.clients.elasticsearch.nodes.info.NodeInfoPath#NodeInfoPath this.repo set a value from ApiTypeHelper.unmodifiableRequired, but builder.repo is null, and there is NPE error.
Please fix this bug in 7.17 and 8 versions.

**Comment by l-trotta** [comment]
fixed as part of [elastic/elasticsearch-java#745](https://github.com/elastic/elasticsearch-java/pull/745)
