### ISSUE TITLE
how can i use  sub-aggregations in java api not use Lambda

### ISSUE THREAD

**Issue by 771724316** [elastic/elasticsearch-java#357]
### Java API client version

8.3.2

### Java version

1.8

### Elasticsearch Version

8.3.2

### Problem description

```
TermsAggregationBuilder aggregationBuilder = AggregationBuilders.terms("age").field("age").size(100);
aggregationBuilder.subAggregation(AggregationBuilders.terms("name").field("name").size(100));
sourceBuilder.aggregation(aggregationBuilder);
```
how can i use 8.3 java client api write the sub agg  Same as above     not use Lambda
This is a headache、help me please

**Comment by 771724316** [comment]
阿斯蒂芬

1. [ ] 

> **_`
Duplicate of #`_**

**Comment by mahuijohn** [comment]
and no doc to follow

**Comment by l-trotta** [comment]
Hey! So if I understood correctly you need to perform an "age" aggregation with a "name" sub aggregation; let me show you first how I would write this using lambdas, given `esClient` as the ElasticsearchClient: 

```
        SearchResponse<Object> subAggLambdas = esClient.search(s -> s
                .index("users")
                .query(q -> q
                    .matchAll(a -> a))
                .aggregations("age", a -> a
                    .terms(ts -> ts
                        .field("age"))
                    .aggregations("name", aa -> aa
                        .terms(tts -> tts
                            .field("name"))))
            , Object.class);
```

while using only builders it would be something like: 

```
        TermsAggregation ts1 = new TermsAggregation.Builder().field("age").size(100).build();
        TermsAggregation ts2 = new TermsAggregation.Builder().field("name").size(100).build();

        Query query = new Query.Builder().matchAll(new MatchAllQuery.Builder().build()).build();
        SearchRequest sr = new SearchRequest.Builder()
            .index("users")
            .query(query)
            .aggregations("age",new Aggregation.Builder().terms(ts1)
                .aggregations("name",new Aggregation.Builder().terms(ts2).build()).build()).build();

        esClient.search(sr,Object.class);
```

writing the lambda version took me a minute, writing the builder versions took me around 10, I think it's much simpler to let the lambdas guide you through the properties you need to set instead of reading the definition of each method to understand which one is the correct builder to use. I hope this helps :)
