### ISSUE TITLE
Remove references to jakarta from co.elastic.clients.json.JsonpMapper

### ISSUE THREAD

**Issue by unoexperto** [elastic/elasticsearch-java#431]
### Description

Hi folks,

I see that you rewrote Java client and instantly I have feature request for you.

I'd like references to jakarta to be removed from `co.elastic.clients.json.JsonpMapper` because current abstraction is not much of an abstraction really because it prevents me from implementing json mapper that uses something other than Jackson. In my case I'd love to use Moshi and I'm ready to contribute the implementation to you.

`JsonMapper` interface should be something like this:

```
import java.io.InputStream;
import java.lang.reflect.Type;

public interface JsonMapper {

    <T> T deserialize(Type type, String json);

    <T> T deserialize(Type type, InputStream source);

    <T> void serialize(Type type, T value);
}
```

Use of `Type` instead of `Class<T>` is intentional so that we can properly serialize generic value such as `List<Map<String, Int>>` whose type will be represented by `ParameterizedTypeImpl`.

I'm looking forward to your feedback, @swallez

**Comment by swallez** [comment]
Thanks for the feedback.

References to Jakarta JSONP can not be removed from `JsonpMapper`, as they represent the stream of JSON events: the one we read from with `JsonParser`, and the one we write to with `JsonGenerator`. All classes of the Java API client use streaming serialization/deserialization and only use an object mapper for application-defined classes such as documents in indexing and search APIs.

The Jackson implementation is a JSONP implementation that wraps Jackson. And you can see in [`JacksonJsonpMapper`](https://github.com/elastic/elasticsearch-java/blob/main/java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpMapper.java) how we move between JSONP and Jackson by requiring that the `JsonParser` and `JsonGenerator` are not arbitrary implementations, but those based on Jackson.

Giving a quick look at Moshi (I never heard of it before), [`JsonReader`](https://github.com/square/moshi/blob/master/moshi/src/main/java/com/squareup/moshi/JsonReader.kt) and [`JsonWriter`](https://github.com/square/moshi/blob/master/moshi/src/main/java/com/squareup/moshi/JsonWriter.kt) seem to be the ones that need to be decorated with implementations of `JsonParser` and `JsonGenerator`.

As for supporting `Type` instead of `Class<?>`, indeed this would allow to work around the limitations of type erasure.

**Comment by unoexperto** [comment]
But you don't have to use JSONP at all. You could have an abstraction on lower level (stream of bytes and/or `String`) and let implementation decide whether they want to use JSONP/Jackson or not. Moshi (as an example) uses it's own internal model of representing json events/primitives.

**Comment by swallez** [comment]
The Java client serialization/deserialization uses generated code to process a stream of JSONP events. This in itself is very fast with very few allocations. There is indeed a small overhead when this JSONP stream is actually a wrapper on top on another implementation of JSON even streams, but this overhead is pretty minimal as it mostly consists in one or two additional method calls per event and we can expect the HotSpot JVM to do a pretty good job at optimizing these.

Also, as can be seen in  [`JacksonJsonpMapper`](https://github.com/elastic/elasticsearch-java/blob/main/java-client/src/main/java/co/elastic/clients/json/jackson/JacksonJsonpMapper.java), when we call Jackson to serialize or deserialize an object, we call it with its native parser which was created from the input stream. So using JSONP in the Java client has zero overhead when we map application classes.

But there's more: some parsers (e.g. Jackson) consider that they "own" the input stream, and will do some buffered reading. What this means is that if we call Jackson to map an application object from the raw input stream, on return the stream may have been consumed further than the end of the object that was deserialized. The Java client API would then not be able to continue parsing the JSON it is responsible for.

All this to say that the lowest level at which we can work is a stream of JSON events. We won't be able to reliably integrate a 3rd party JSON parser when working at the input stream level.

We made the choice of using JSONP because it's the common Jakarta-EE specification, and its minimalism allows it to be easily implemented on top of other implementations of streaming JSON parsers, incuding Moshi as far as I can tell. We won't change this decision 😉

**Comment by unoexperto** [comment]
> We won't change this decision

That's ok :) I appreciate your time explaining your position to me!

**Comment by swallez** [comment]
Thanks! So I guess we can close this issue.
