### ISSUE TITLE
component_template API is missing in ElasticsearchIndicesClient

### ISSUE THREAD

**Issue by sothawo** [elastic/elasticsearch-java#520]
### Java API client version

8.6.2

### Java version

17.0.6

### Elasticsearch Version

8.6.2

### Problem description

The indices client (`co.elastic.clients.elasticsearch.indices.ElasticsearchIndicesClient`) is missing the methods to work with component templates.

It provides the call `ElasticsearchIndicesClient#putIndexTemplate(PutIndexTemplateRequest)` which allows to store an index template, and in that request it is possible to define the components that this template if built of. (property `composedOf` in the request object).

But it is not possible to define these components as there are no methods available to put, retrieve or delete them.

I have not been able to find any of

* https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-component-template.html
* https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-component-templates.html
* https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-delete-component-template.html

in the indices client

**Comment by swallez** [comment]
For some reason [these APIs are part of the `cluster` namespace](https://github.com/elastic/elasticsearch/blob/main/rest-api-spec/src/main/resources/rest-api-spec/api/cluster.put_component_template.json) and you can find them in `ElasticsearchClient.cluster()`.

We (ES clients team) decided to stick with this location in order to avoid any potential future conflict if the ES dev team decides to add similarly-named endpoints in the `indices` namespace.

Closing the issue, feel free to reopen if there are additional issues on these endpoints.
