### ISSUE TITLE
Error deserializing co.elastic.clients.elasticsearch._types.analysis.HtmlStripCharFilter: Unknown field 'escaped_tags'

### ISSUE THREAD

**Issue by lengoyvaerts** [elastic/elasticsearch-java#528]
### Java API client version

8.6.2

### Java version

17

### Elasticsearch Version

8.6.2

### Problem description

While trying to create a new index using the Elastic Java Client API, I stumble across the following exception:

`Error deserializing co.elastic.clients.elasticsearch._types.analysis.HtmlStripCharFilter: Unknown field 'escaped_tags' (JSON path: settings.index.analysis.char_filter.html_body_filter.escaped_tags)`

Code:

```
public void createIndex(String index, String settingsJson) throws IOException {
  LOG.info("Creating index {}", index);
  CreateIndexRequest request = new CreateIndexRequest.Builder()
                .index(index)
                .withJson(new StringReader(settingsJson))
                .build();
  elasticsearchClient.indices().create(request);
}
```
where the settings json contains the following:

```
...
"char_filter": {
  "html_body_filter": {
    "type": "html_strip",
    "escaped_tags": [
      "body"
    ]
  }
}
...
```

[According to the documentation](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/analysis-htmlstrip-charfilter.html#analysis-htmlstrip-charfilter-configure-parms), this is a valid configurable parameter.

**Comment by lengoyvaerts** [comment]
Created a PR for this

https://github.com/elastic/elasticsearch-java/pull/530

**Comment by l-trotta** [comment]
Hello, thanks for reporting this! You're correct, `escaped_tags` seems to be missing from the [API specification definition](https://github.com/elastic/elasticsearch-specification) used to generate the java client. We'll fix it and then update the client to solve this issue. Also thank you very much for wanting to contribute to the client with a PR, but unfortunately, since it's autogenerated, it would get overwritten at the next generation; for this reason I'll close it.
