### ISSUE TITLE
SingleMetricAggregateBase#value should be nullable like valueAsString - 

### ISSUE THREAD

**Issue by MT-Jacobs** [elastic/elasticsearch-java#537]
### Java API client version

7.17.4

### Java version

11

### Elasticsearch Version

8.2.2

### Problem description

This is a follow-up to https://github.com/elastic/elasticsearch-java/issues/155 where the issue was originally described.

My original workaround of checking the document count is insufficient. It is possible that we may attempt to calculate the min/max values for a field that aren't present in a document:

``` json
{
    "aggregations": {
        "max_total_rate": {
            "max": {
                "field": "estTotalRate"
            }
        },
        "min_total_rate": {
            "min": {
                "field": "estTotalRate"
            }
        }
    },
    "query": {
        "bool": {
            "filter": []
        }
    },
    "size": 0
}
```

In the above example, if there are no documents with `estTotalRate`, the document count can be nonzero and thus break this workaround:

``` kotlin
fun MultiBucketBase.nullableAvg(name: String): Double? = when (this.docCount())
{
    0L -> null
    else -> this.aggregations()[name]?.avg()?.value()
}
```

**Comment by f-loris** [comment]
We also ran into this issue while migrating from HLRC to this client and this topic is currently a blocker for us.
I'd highly appreciate a deeper discussion on this topic. 

I've seen that currently this is implemented as a primitive double due to avoiding boxing of values (see. https://github.com/elastic/elasticsearch-java/issues/155#issuecomment-1160672969) But the statement that it can be deduced based on the document count from @swallez seems to be incorrect to me. Besides the example above also script fields make it impossible to deduce it based on the document count.

Therefore, by simply converting any `null` to `0` completely hides the information that there is no value available as `0` could be a valid result of an aggregation. Wouldn't a value like `Double.POSITIVE_INFINITY` be a better alternative? This was also the behavior when using the HLRC as far as I can tell.  It also wouldn't require any boxing.

**Comment by l-trotta** [comment]
Hello, sorry for the delay. Unfortunately our opinion on the matter is still the same described in the [comment](https://github.com/elastic/elasticsearch-java/issues/155#issuecomment-1160672969) from issue #155: since it's always possible to find a workaround to understand whether the return value is a "real" zero, we would prefer not to change the current behaviour. For example in this specific case where fields are missing from the document a possible workaround would be to add a filter query before, like: 

```
{    
  "query": {
      "exists": {
        "field": "estTotalRate"
      }
    },
    "aggregations": {
        "max_total_rate": {
            "max": {
                "field": "estTotalRate"
            }
        },
        "min_total_rate": {
            "min": {
                "field": "estTotalRate"
            }
        }
    },
    "size": 0
}
```
so to keep the doc count meaningful.

**Comment by f-loris** [comment]
@l-trotta the comment only mentions the issue of boxing/unboxing. But what about my proposal from above about keeping the old logic from the deprecated HLRC using a value like `Double.POSITIVE_INFINITY`? There no boxing would happen. As your comment already stated, there are only "workarounds", but no real good solutions currently. 
Would be great to hear your opinion on that.

**Comment by l-trotta** [comment]
The problem with infinity is that it doesn't exist in json, so we think it would be even more confusing for users, considering that we try to keep the client consistent with the json REST API where possible. Also, modifying this behaviour would result in breaking changes to the client, which we try to avoid except for bug fixes.
