### ISSUE TITLE
PutIndexTemplateRequest and PutComponentTemplateRequest lack allow_auto_create field

### ISSUE THREAD

**Issue by ztyzbb** [elastic/elasticsearch-java#571]
### Description

Both PutIndexTemplateRequest and PutComponentTemplateRequest lacks allow_auto_create field.
[Create or update component template API](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/indices-component-template.html)
[Create or update index template API](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/indices-put-template.html)
Index template API's doc didn't list this field but it just works when you PUT it.
Hope can backport to 7.17, thank you!

**Comment by l-trotta** [comment]
Hello, thank you for reporting this! While it looks like `PutComponentTemplateRequest` was already fixed with [this PR ](https://github.com/elastic/elasticsearch-specification/pull/2155), `PutIndexTemplateRequest` is still missing `allow_auto_create`; I'll have to investigate this a bit more since it's missing from the documentation as well. If it's actually an accepted parameter then we'll fix the [API specification](https://github.com/elastic/elasticsearch-specification) and regenerate the java code from it. Thank you!

**Comment by l-trotta** [comment]
So, after investigating it turns out there were some mistakes in the documentation, PutComponentTemplateRequest actually doesn't allow `allow_auto_create`, while PutIndexTemplateRequest does, and there are also other fields with similar mistakes. This [specification PR](https://github.com/elastic/elasticsearch-specification/pull/2488) fixes those mistakes for the clients, the docs will be fixed in the future.
