### ISSUE TITLE
IndicesOptions for all requests

### ISSUE THREAD

**Issue by bilak** [elastic/elasticsearch-java#606]
### Description

Hello,
in previous version [<8.x] it was possible to create `GetIndexRequest` with `IndicesOptions`. The new `co.elastic.clients.elasticsearch.indices.GetIndexRequest` doesn't contain these options and it's always needed to add them through builder. Would it be possible to add `IndicesOptions` as builder field? It's used for example in `SearchInputRequestDefinition`.

Benefit: it will be easier to provide default config for multiple requests.

**Comment by l-trotta** [comment]
Hello, the reason for the difference between those two requests in the new java client is because they are different in the JSON representation, which the new client tries to stay as close to as possible. In the official documentation for [GetIndex](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-index.html#get-index-api-query-params), those options are query parameters, while in [SearchInputhttps](https://www.elastic.co/guide/en/elasticsearch/reference/current/input-search.html#search-input-attributes) it's a setting object, and the new client reflects that.
