### ISSUE TITLE
nodes().stats() doesn't return node version

### ISSUE THREAD

**Issue by mightycoco** [elastic/elasticsearch-java#707]
### Java API client version

8.10.3

### Java version

20.0.2

### Elasticsearch Version

8.9.0

### Problem description

Using the rest endpoint _nodes/process I was accessing the 
node[].name
node[].version
node[].roles
The endpoint nodes().stats().nodes() only returns name and roles but not the node version.

co.elastic.clients.elasticsearch.nodes.Stats resp. co.elastic.clients.elasticsearch.nodes.Stats.Builder used in co.elastic.clients.elasticsearch.nodes.NodesStatsResponse doesn't contain a version field.

<div><del>Additionally I couldn't find a way to reduce the amount of information to be transferred over the wire. Whilst the rest endpoints _nodes/process returns only basic information + process, _nodes/_all returns everything.

However, the java API doesn't allow to request only the basic information + process but always transfers everything to be deserialized.
Expected in .nodes().stats(s->s.fields("process")) only the process field is being requested and all other fields (except basic information) is null, butt all data is requested and requested and returned.</del></div>

reducing the responded fields must be done using metrics:
```java
client.nodes().stats(s->s.metric("process"))
```

**Comment by l-trotta** [comment]
Hello, thanks for reporting this! Seems like we're missing some fields in the [API specification](https://github.com/elastic/elasticsearch-specification) used to produce the Java code, we'll add them and regenerate the client code to fix this issue.

**Comment by l-trotta** [comment]
Hey! So in elasticsearch calling `_nodes/process` just means calling `_nodes` and then just filtering `process` out of all the information `_nodes` returns, so the direct equivalent of doing that in the java client is to call:
```
client.nodes().info();
```
and retrieving the desired node info, which will then contain both `process` and `version`.
This endpoint was broken because of some mismatching optional type, it will be fixed in the next version. Thank you for your patience!
