### ISSUE TITLE
UpdateOperation is not able to use docAsUpsert or script options yet

### ISSUE THREAD

**Issue by VincentMLiu** [elastic/elasticsearch-java#72]
I'm trying to build a Bulk request with some upsert operations, but it seems not supported in this version's Java Client yet.
 I've seen the **docAsUpsert** and **Script** in the UpdateRequest. Will these options be supported at UpdateOperation in the next version?

**Comment by swallez** [comment]
This has been fixed in PR #125

Bulk update operations now contain an `UpdateAction` that has these properties. See example from the tests below:

https://github.com/elastic/elasticsearch-java/blob/8bc1f21dd7826bd6bb553038ff8a2bb8cb69c953/java-client/src/test/java/co/elastic/clients/elasticsearch/end_to_end/RequestTest.java#L210-L217
