### ISSUE TITLE
Regarding termvectors query related issues

### ISSUE THREAD

**Issue by asdaerwrte** [elastic/elasticsearch-java#783]
### Java API client version

8.8.1

### Java version

8

### Elasticsearch Version

8.8.1

### Problem description

In the case where the ID query is not applicable, the returned value does not have an ID, but your verification ID cannot be empty in any case
![image](https://github.com/elastic/elasticsearch-java/assets/166780744/e74bb62e-d6b6-44c4-a32e-2312a4ad2eb7)
![image](https://github.com/elastic/elasticsearch-java/assets/166780744/3ca8b0ab-acc8-4b1d-88b3-10618dfe1703)

**Comment by l-trotta** [comment]
Hello, thanks for the report! Yes, `id` in TermVectorResponse should be optional since the server doesn't return it when it's not specified in the request. We'll fix it in the [API specification](https://github.com/elastic/elasticsearch-specification) used to produce the Java code and regenerate the client to fix it.
