### ISSUE TITLE
`field_masking_span` is deprecated in ES8.0+ but still used in java client 

### ISSUE THREAD

**Issue by vdemay** [elastic/elasticsearch-java#809]
### Java API client version

8.13.4

### Java version

11

### Elasticsearch Version

8.13.4

### Problem description

Hello, 

Since ES8.0 `field_masking_span` is deprecated in favor of `span_field_masking`. Ref: https://github.com/elastic/elasticsearch/pull/74718/files

This change is not reflected to `elasticsearch-java` client causing exception on ES: `deprecated fields not supported here but got [field_masking_span] which has been replaced with [span_field_masking]`

I've made this [PR](https://github.com/elastic/elasticsearch-java/pull/808) to propose a fix. (I signed the agreement right after creating the PR making the validation failed - sorry about that :) ) 

Thanks for your help

**Comment by l-trotta** [comment]
Hello, thank you for reporting this! Unfortunately we cannot accept PRs in this repo since the java client is 99% [autogenerated](https://github.com/elastic/elasticsearch-java/blob/main/CONTRIBUTING.md) from our [api-specification](https://github.com/elastic/elasticsearch-specification). If you want you can contribute there to fix the issue for all clients :D otherwise we'll do it. Thanks!

**Comment by vdemay** [comment]
Hello, thanks for your answer. I'll do

**Comment by l-trotta** [comment]
Thanks again for providing a fix! Closing this as it will be part of the next minor release :)
