### ISSUE TITLE
PutTemplateRequest - `Unknown field 'composed_of'`

### ISSUE THREAD

**Issue by mdgilene** [elastic/elasticsearch-java#814]
### Java API client version

8.7.1

### Java version

17

### Elasticsearch Version

7.17.5

### Problem description

Attempting to create a index template following the updated documentation recommending the usage of composable index templates with component templates. (https://www.elastic.co/guide/en/elasticsearch/reference/current/index-templates.html)

```
Caused by: co.elastic.clients.json.JsonpMappingException: Error deserializing co.elastic.clients.elasticsearch.indices.PutTemplateRequest: Unknown field 'composed_of'
```

```java
client.indices()
    .putTemplate(
        r -> r.withJson(new StringReader("""
            {
                "composed_of": "my_component_template"
            }
            """))
            .name("my_index_template")
            .indexPatterns("prefix-*")
```

Note how I even had to use `withJson` to even set the `composed_of` property because there is no method for it.

**Comment by l-trotta** [comment]
Hello! Yes the [api specification](https://github.com/elastic/elasticsearch-specification) used to produce the java client code didn't match the server code perfectly for template requests up until recently when it was fixed with [this PR](https://github.com/elastic/elasticsearch-specification/pull/2488); updating the client to the latest version should fix the issue.
