### ISSUE TITLE
Why is the JAR so big for the library in java ?

### ISSUE THREAD

**Issue by alois-git** [elastic/elasticsearch-java#878]
Hi,

Looking at the library JAR size, 11M is kind of crazy and make our JAR quite big, I am wondering why is it so big ? 

Regards,

Aloïs

**Comment by l-trotta** [comment]
Hello! The client is that big because of the amount of endpoints and classes that it has to model to be fully compatible with the elasticsearch server. We handle ~500 endpoints and model ~3500 different classes! There aren't many transitive dependencies and they weight just a few KBs, so the whole weight of the client is simply due to a massive amount of java classes.
